### ISSUE TITLE
cloudi_service_db_riak constraing warning when building with rebar3

### ISSUE THREAD

**Issue by ReuvenSwirsky** [gbour/letsencrypt-erlang#1]
Everything seems to work, but out of the box, we get this warning. 

I tried explicitly fixing the constraint, but it seems to work anyway despite the warning so it's probably no big deal.

===> [cloudi_service_oauth1:1.5.1] Only existing version of cloudi_service_db_riak is 1.3.3 which does not match constraint ~> 1.5.1. Using anyway, but it is not guaranteed to work.

**Comment by gbour** [comment]
Hello @chatterbeak, thanks for your report.
I digged a bit, and cloudi_service_oauth is referenced in shotgun erlang.mk (as part of erlang.mk package index), shotgun being itself a dependency of letsencrypt-erlang.
Not sure how rebar3 is considering erlang.mk file.

cloudi_service_oauth1 is not used anywhere in letsencrypt-erlang or any of its dependencies, so this error should not impact letsencrypt-erlang behavior

**Comment by gbour** [comment]
I got a response from tristan (one of rebar3/hex.pm creators) on erlanger slack.
this warning is related to rebar3 registry update, and missing cloudi_service_db_riak 1.5.1 dependency on hex.pm.
It has no impact on letsencrypt-erlang 

```

tristan
2:31 PM @gbo: that is just a warning about the registry being updated
2:33
it is unrelated to your project. it will only show when the registry is updtaed, which happens if you run
rebar3 update or if you run compile on a project with a dep that it can't find so it automatically runs an update
```
