### ISSUE TITLE
hex package is missing dependencies

### ISSUE THREAD

**Issue by Licenser** [gbour/letsencrypt-erlang#5]
hex package misses dependencies.

Hi the hex package does not have any dependenceis that's a bit of a problem would it be possible to fix this? It pretty much requires to use hex packages as dependencies too.

**Comment by gbour** [comment]
Hi @Licenser, thanks for the report

Using hex dependencies requires a bit of work, as packaged cowboy version is older than the one I use (1.0.4 vs 2.0.0-pre2).
But I'm working on it and it should be ready soon :)

**Comment by gbour** [comment]
I'm kind of stuck now because cowboy and shotgun are mutually exclusive on hex.pm (see the discussion on slack channel https://erlanger.slack.com/archives/rebar3/p1473953453000145).
I will probably have to replace one or the other to be able to publish letsencrypt-erlang on hex.pm

**Comment by gbour** [comment]
this is fixed with 0.7.0 release
